<a href="https://colab.research.google.com/github/KanishkIngle/Academic/blob/master/Gaussian_Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

def forward_elimination(A, b, n):
    """
    Calculates the forward part of Gaussian elimination.
    """
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor = A[i,row] / A[row,row]
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j]

            b[i] = b[i] - factor * b[row]

        print('A = \n%s and b = %s' % (A,b))
    return A, b

def back_substitution(a, b, n):
    """"
    Does back substitution, returns the Gauss result.
    """
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / a[n-1, n-1]
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = sums - a[row,j] * x[j]
        x[row] = sums / a[row,row]
    return x

def gauss(A, b):
    """
    This function performs Gauss elimination without pivoting.
    """
    n = A.shape[0]

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))

    A, b = forward_elimination(A, b, n)
    return back_substitution(A, b, n)

# Main program starts here
if __name__ == '__main__':
    A = np.random.randint(1,100,size=(5,5))
    b = np.random.randint(1,100,size=5); B.shape = (5, 1)
    x = gauss(A, b)
    print('Gauss result is x = \n %s' % x)

A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0  -46   46 -228   27]
 [   0  -33  -22 -243    6]
 [   0   47  -21 -186  -15]] and b = [ 34  18 -73 -80 -30]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0  -21 -254   28]
 [   0    0  -22 -169  -47]] and b = [ 34  18 -62 -72 -40]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0 -283  -19]] and b = [ 34  18 -62 -99 -69]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
Gauss result is x = 
 [[ 0.30759199]
 [ 0.40988339]
 [ 0.160186  ]
 [ 0.25325987]
 [-0.13333333]]


Finding the Time Complexity for Gauss Jordan ELimination

In [25]:
start = time()
for i in range(10000):
    x1 = gauss(A,b)
print('Time = ', time() - start)


Streaming output truncated to the last 5000 lines.
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
A = 
[[  20   16   15   83   16]
 [   0   78    2  -28   54]
 [   0    0   47 -244   58]
 [   0    0    0 -363   53]
 [   0    0    0    0  -60]] and b = [ 34  18 -62 -99   8]
A = 
[[  2