<a href="https://colab.research.google.com/github/KanishkIngle/Academic/blob/master/LU_decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve
from time import time

In [12]:
#  Define a system of linear equations. A  is the coefficient matrix and b is the vector of knowns
#  We are using the same matrix as above
A = np.random.randint(1,100,size=(5,5))
b = np.random.randint(1,100,size=5); b.shape = (5, 1)

#  Do the matrix factorization.  In our case, the permutation matrix P is the identity
P, L, U = lu(A)

print('The L matrix is:')
print(L)
print()
print('The U matrix is:')
print(U)

#  Show the A = PLA
np.allclose(L @ U, A)


The L matrix is:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.7032967   1.          0.          0.          0.        ]
 [ 0.24175824 -0.59474805  1.          0.          0.        ]
 [ 0.96703297 -0.44144784 -0.24257812  1.          0.        ]
 [ 0.46153846 -0.47196593 -0.44569094  0.65652118  1.        ]]

The U matrix is:
[[ 91.          86.          75.           9.          43.        ]
 [  0.         -15.48351648  32.25274725   3.67032967  61.75824176]
 [  0.           0.          30.05039035  17.00709723  88.33498935]
 [  0.           0.           0.          20.04251199  92.10875983]
 [  0.           0.           0.           0.          60.20038533]]


False

In [13]:
#  Do the factorization
LU, p = lu_factor(A)

#  Solve the system
x1 = lu_solve((LU, p), b)
print(x1)

#  Does this give the same results as linalg.solve?
np.allclose(x1, np.linalg.solve(A, b))


[[ 4.1692405 ]
 [-3.4769653 ]
 [-1.39700862]
 [ 3.52508278]
 [ 0.13181469]]


True

In [27]:
start = time()
for i in range(10000):
    x1 = np.linalg.inv(LU)
print('Time = ', time() - start)


Time =  0.16279292106628418
